name: Print Name

on:
  workflow_call:

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Name from Org A
        uses: Pranjal-1515/Test-Shared/.github/workflows/Test-A.yml@main
        id: fetch-name
    
      - name: Print Name Value
        run: |
           echo "The name value is: ${{ steps.fetch-name.outputs.name }}"

