name: Print Name via Shared

on:
  workflow_call:
     inputs:
        variable_path:
           type: string
           required: true

jobs:
  fetch-name:
    uses: ${{ inputs.variable_path }}

  print-name:
    needs: fetch-name
    runs-on: ubuntu-latest
    steps:
      - name: Print Name Value
        run: |
          echo "name: \"${{ needs.fetch-name.outputs.name }}\"" > config.yml
          echo "others: \"${{ needs.fetch-name.outputs.others }}\"" >> config.yml

      - name: Print config.yml
        run: |
          cat config.yml    

          
