name: Print Name via Shared

on:
  workflow_call:

jobs:
  fetch-name:
    uses: Pranjal-1515/Test-A/.github/workflows/Pass_Variable.yaml@main

  print-name:
    needs: fetch-name
    runs-on: ubuntu-latest
    steps:
      - name: Print Name Value
        run: |
          echo "name: \"${{ needs.fetch-name.outputs.name }}\"" > config.yml
          echo "others: \"${{ needs.fetch-name.outputs.others }}\"" >> config.yml

      - name: Print config.yml
        run: |
          cat config.yml    

          
